name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Commit and push changes
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Leon Stafford"
          git config user.email "me@ljs.dev"
          git config --global credential.helper cache
          git config --global credential.helper 'store --file=.git/credentials'
          echo "https://${GITHUB_TOKEN}:x-oauth-basic@github.com" > .git/credentials
          git add dist
          git diff --quiet && git diff --staged --quiet || git commit -m "Build new dist"
          git push
